### ISSUE TITLE
No development teams detected

### ISSUE THREAD

**Issue by alper** [wusyong/cargo-mobile#100]
I've peeked through the code but the check for development teams goes through the certificates on my machine?

In my case it can't find anything:
```
Detected development teams:
  -- none --
  Enter an index for a team above, or enter a team ID manually.
```

To manually enter this it's also not entirely clear where I could find this ID. developer.apple.com does not really list something like this.

**Comment by lucasfernog** [comment]
Yeah you need a developer ID certificate installed in your keychain. Usually the name will be displayed like `Developer ID Application: APP_NAME (TEAM_ID_HERE)`. If you do have a certificate installed, you'll be able to find it in the Keychain Access app.

**Comment by alper** [comment]
OK. That fixed that.

(Not sure anybody really does that anymore since Xcode manages everything automatically these days.)

**Comment by lucasfernog** [comment]
Was your certificate installed already? If so that's an issue on this crate.

**Comment by alper** [comment]
No I got it manually from the Apple Developer portal and installed it into the login keychain.

**Comment by lucasfernog** [comment]
Well if there's a way to automate this I would love to investigate.
