### ISSUE TITLE
WASM trunk not working android(blank screen, 100%)

### ISSUE THREAD

**Issue by Xyndra** [wusyong/cargo-mobile#118]
It is spamming
```
29581 29581 E Tauri/Console: File: https://tauri.localhost/ - Line 544 - Msg: WebSocket connection to 'wss://tauri.localhost/_trunk/ws' failed: Error in connection establishment: net::ERR_CONNECTION_REFUSED
```
and looks like this
![image](https://user-images.githubusercontent.com/71836523/226165398-652f3d82-b2db-4d43-9549-3fee6ef5e664.png)

**Comment by amrbashir** [comment]
try using my fork https://github.com/amrbashir/trunk for now until upstream merges the PRs I sent.

**Comment by Xyndra** [comment]
> try using my fork https://github.com/amrbashir/trunk for now until upstream merges the PRs I sent.

### 1. Please add an issues tab
### 2. How am I supposed run this

**Comment by amrbashir** [comment]
1. Issues is now activated for the fork
2. `cargo install trunk --git https://github.com/amrbashir/trunk`

**Comment by Xyndra** [comment]
thanks 👍
