### ISSUE TITLE
Cargo mobile init appears to be stuck in iOS toolchain installation step

### ISSUE THREAD

**Issue by mlthlschr** [wusyong/cargo-mobile#132]
Hi, 

my plan was to try out the example app for iOS. I followed the instructions in the readme. 

The first try of `tauri mobile init` failed due to missing XCode (I recently updated to MacOS 13.3 which apparently rendered the old XCode version unusable). After updating XCode I tried it again, but now it is stuck at 

```
malte@mm tauri-mobile-test % cargo mobile init     
Generating base project...
Installing iOS toolchains...
info: component 'rust-std' for target 'aarch64-apple-ios' is up to date
info: component 'rust-std' for target 'aarch64-apple-ios-sim' is up to date
info: component 'rust-std' for target 'x86_64-apple-ios' is up to date

```

When running `cargo mobile doctor` I get the following:

```
malte@mm tauri-mobile-test % cargo mobile doctor

[✔] cargo-mobile v0.3.0
    • Contains commits up to "Publish New Versions (#123)"
    • Installed at "~/.tauri-mobile"
    • macOS v13.3 (22E252)
    • rustc v1.68.2 (9eb3afe9e 2023-3-27)

[!] Apple developer tools
    • Xcode v14.3
    • Active developer dir: "/Applications/Xcode.app/Contents/Developer"
    • ios-deploy v1.12.1
    • XcodeGen v2.34.0
    ✗ xcode-rust-plugin plugin absent
    ✗ xcode-rust-plugin lang spec absent
    ✗ xcode-rust-plugin lang metadata absent
    ✗ xcode-rust-plugin is outdated
    ✗ Failed to check xcode-rust-plugin UUID status: Failed to read plist at
      "/Users/malte/.tauri-mobile/checkouts/rust-xcode-plugin/Plug-ins/Rust.ideplugin/Contents/Info.plist": No such file or directory (os error 2)

[!] Android developer tools
    ✗ Have you installed the Android SDK? The `ANDROID_HOME` environment variable isn't set, and is required: environment variable not found

[✔] Connected devices
    • No connected devices were found
```

I tried to fix the dev tools problems by manually cloning xcode-rust-plugin and copying the files to the XCode folders, but `cargo mobile init` still does not go further than before.

**Comment by wusyong** [comment]
I also had this issue before and I had to change wifi to work.
Unfortunately I can't reproduce it anymore.
Maybe you tried to use your phone's hotspot.

@lucasfernog Considering tauri uses this repo as lib. I wonder does this happen to tauri-cli before?

**Comment by mlthlschr** [comment]
That was it. I was connected via Ethernet, I turned it off and used Wifi instead. Then it took a second to go ahead with the initialization.

Strange anyways.

**Comment by lucasfernog** [comment]
I never had this issue, but if it happens here then it'll also happen with the Tauri CLI.
