### ISSUE TITLE
rustup could not choose a version of cargo to run

### ISSUE THREAD

**Issue by lovelindhoni** [wusyong/cargo-mobile#133]
Hi there,
I am facing an error such as that rustup could not choose a toolchain on both dev and build commands.
I ran `rustup default stable-msvc` several times and I even tried reinstalling rust.

![Untitled](https://user-images.githubusercontent.com/100030865/232061024-cda2ef97-4094-4748-87c1-b0dae14186ba.png)

![Untitled](https://user-images.githubusercontent.com/100030865/232064575-6f6af9a4-a328-4fe9-a1e5-fc436cde7999.png)

**Comment by FabianLars** [comment]
Is it possible that you have multiple rustup or cargo installations? Maybe you installed it in a different way (other than via rustup.rs) before and there are still left-overs that conflict with the new one?

**Comment by lovelindhoni** [comment]
Thanks man,
I cleared temp files, appdata and some registry keys and the env's which I created for custom installation path and it worked out pretty good.
