### ISSUE TITLE
Failed to assemble APK     program not found

### ISSUE THREAD

**Issue by davehorner** [wusyong/cargo-mobile#154]
```
cargo android run
[2023-05-05T01:14:58Z DEBUG tauri_mobile::util::cli::interface] raw args: [
        "C:\\Users\\dhorner\\.cargo\\bin\\cargo-android.exe",
        "run",
    ]
[2023-05-05T01:14:58Z INFO  tauri_mobile::config::raw] looking for config file at "\\\\?\\C:\\working\\whosball\\mobile.toml"
[2023-05-05T01:14:58Z INFO  tauri_mobile::config::raw] found config file at "\\\\?\\C:\\working\\whosball\\mobile.toml"
[2023-05-05T01:14:58Z INFO  tauri_mobile::templating] checking for template pack "wry" at "C:\\Users\\dhorner\\.cargo\\.tauri-mobile\\templates/apps\\wry.toml"
[2023-05-05T01:14:58Z INFO  tauri_mobile::templating] checking for template pack "wry" at "C:\\Users\\dhorner\\.cargo\\.tauri-mobile\\templates/apps\\wry"
[2023-05-05T01:14:58Z INFO  tauri_mobile::templating] found template pack "wry" at "C:\\Users\\dhorner\\.cargo\\.tauri-mobile\\templates/apps\\wry"
 (moto g stylus 5G (2022)) with target "aarch64-linux-android"
[2023-05-05T01:14:59Z INFO  tauri_mobile::util::cli::interface] exiting with RunFailed(
        ApkError(
            AssembleFailed(
                Error {
                    kind: NotFound,
                    message: "program not found",
                },
            ),
        ),
    )
error: Failed to assemble APK
    program not found
```
rustup shows the toolchain installed.
```
installed targets for active toolchain
--------------------------------------

aarch64-linux-android
armv7-linux-androideabi
i686-linux-android
x86_64-linux-android
x86_64-pc-windows-msvc
```

I know it's not flutter development but doctor has useful info.
```
flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 3.3.10, on Microsoft Windows [Version 10.0.19044.2846], locale en-US)
[√] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
[√] Chrome - develop for the web
[√] Visual Studio - develop for Windows (Visual Studio Community 2022 17.4.3)
[√] Android Studio (version 2021.3)
[√] VS Code, 64-bit edition (version 1.74.2)
[√] Connected device (4 available)
[√] HTTP Host Availability

• No issues found!
```

any help would be greatly appreciated.

**Comment by amrbashir** [comment]
Could you check if `<project-dir>/gen/android/<app-name>/gradlew.cmd` exists?

**Comment by davehorner** [comment]
Not sure what caused it to start working (i updated my jdk) but it is there now.
I am linking and getting the following:
```
= note: ld: error: unable to find library -lgcc
```
I'm running on windows.

**Comment by davehorner** [comment]
I tried setting this up on another machine and found the same issue:
```
error: Failed to assemble APK
    program not found
```

I ran cargo mobile init a second time.  It then works.

On this machine (another windows machine), I had no issue linking and actually ran the app on my phone.

nice work!  thanks.

**Comment by amrbashir** [comment]
> Not sure what caused it to start working (i updated my jdk) but it is there now. I am linking and getting the following:
> 
> ```
> = note: ld: error: unable to find library -lgcc
> ```
> 
> I'm running on windows.

You're probably using an older NDK or rustc version

> I ran cargo mobile init a second time. It then works.

yeah you need to call `cargo mobile init` at least one time on the project (so it generates `gen` folder) before you can use other commands

**Comment by wusyong** [comment]
I also encountered gcc linking erro. It's because of we removed the linking workaround in https://github.com/tauri-apps/tauri-mobile/pull/125 since newer version of rustic can link NDK's GCC correctly now.
If you also see error like this, try `rustup update` to newer version of rustc.
