### ISSUE TITLE
Failed to install CodeLLDB extension

### ISSUE THREAD

**Issue by tkkcc** [wusyong/cargo-mobile#167]
`cargo mobile init` gives

```sh 
Generating base project...
error: Failed to install CodeLLDB extension
    No such file or directory (os error 2)
```
I don't use vscode, seems related to it.

**Comment by tkkcc** [comment]
ok, it works with `cargo mobile init --skip-dev-tools`, may be it can be more friendly?

**Comment by amrbashir** [comment]
That's weird, the tool checkes if `code` command exists first then tries to install the extension.  what's your system information? and what does `code -v` output in shell?

**Comment by tkkcc** [comment]
archlinux, no `code` executable in PATH
```txt
~/b/mizuki cargo mobile init
Generating base project...
error: Failed to install CodeLLDB extension
    No such file or directory (os error 2)
~/b/mizuki code -v
fish: Unknown command: code
~/b/mizuki which -a code
which: no code in (/home/bilabila/toolchains/bin:/home/bilabila/toolchains:/home/bilabila/bin/scripts:/home/bilabila/.local/bin:/home/bilabila/.cargo/bin:/usr/local/sbin:/usr/local/bin:/usr/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl)
```

**Comment by tkkcc** [comment]
`command` gives no output, return code is 1
```txt
[bilabila@bilabilax mizuki]$ command -v code
[bilabila@bilabilax mizuki]$ echo $?
1
[bilabila@bilabilax mizuki]$
```

**Comment by tkkcc** [comment]
https://github.com/tauri-apps/tauri-mobile/blob/4f3e4d71af9282a2a5d054a49324909df3884a7a/src/os/linux/mod.rs#L165-L168

seems it's not quote, it's the problem

```txt
[bilabila@bilabilax mizuki]$ sh -c 'command -v code'; echo $?
1
[bilabila@bilabilax mizuki]$ sh -c command -v code; echo $?
0
[bilabila@bilabilax mizuki]$
```

**Comment by amrbashir** [comment]
Nice finding, would appreciate if you open a PR to fix it

**Comment by tkkcc** [comment]
hope you would make it. i prefer libs like which-rs, and it's more work, and i have no time. (o_ _)ﾉ

**Comment by amrbashir** [comment]
No worries, I will open a PR, thanks for your help
