### ISSUE TITLE
Rotating display on Android results in crash/freeze

### ISSUE THREAD

**Issue by sutheim** [wusyong/cargo-mobile#180]
**Describe the bug**
Creating a new project with any of the templates results in either a crash when rotating display in the case of Wry; or freezes in the case of egui, on my Pixel 7 running Android 13. The app can be started in any orientation. 
This is after following the prerequisites guide for Tauri mobile. Was able to create a regular tauri app and run that on Android without this issue.

From logcat it seems related to the Android Context, as at least with the crash there is a panick at 'assertion failed: previous.is_none()' in [ndk-context lib.rs](https://github.com/rust-mobile/ndk-context/blob/0eb252bf2306f6ca477430a35e88298e634c0b24/ndk-context/src/lib.rs#L100C9-L100C9), but I know very little about Android development.

**Steps To Reproduce**
install prerequisites as per [Tauri guide](https://next--tauri.netlify.app/next/guides/getting-started/prerequisites/windows/)
cargo install --git https://github.com/tauri-apps/tauri-mobile
cargo mobile init
	- select Wry template
cargo android run
change orientation of device after launch

**Platform and Versions:**
Host OS: Windows 11
Target OS: Android 13 on a Pixel 7
Rustc: stable msvc 1.70
cargo-mobile v0.5.1
    • Contains commits up to "fix(linux): fix command detection (#174)\n"
    • SDK v26.1.1
    • NDK v25.2.9519653

**Comment by amrbashir** [comment]
`tauri-mobile` repo is meant as a low level library for tauri, could you please explain how you got here so we could improve the documentation a bit?

**Comment by amrbashir** [comment]
I assume you want to create a Tauri mobile app? in that case, please follow https://tauri.app/blog/2023/03/01/create-tauri-app-version-3-released/#tauri-20-alpha--mobile-support to create one and see if it has the rotating issue or not.

**Comment by sutheim** [comment]
I see thanks for the guidance! I might've misunderstood the responsibility of this repo and was just blindly following the main readme thinking it was a quick way to get a Tauri egui/wry project going.

So I guess this repo is not intended for direct usage and I should use create-tauri-app and setup tauri-egui myself, or use regular cargo-mobile if I only need egui.
