### ISSUE TITLE
Find a satisfying solution for problems related to Gradle compatibility matrix

### ISSUE THREAD

**Issue by JohnScience** [wusyong/cargo-mobile#209]
**Is your feature request related to a problem? Please describe.**
I've been trying to mix and match different versions of JDKs and Gradle, trying to satisfy the [Compatibility Matrix](https://docs.gradle.org/current/userguide/compatibility.html). However, I still haven't found a way to satisfy everything.

**Describe the solution you'd like**
I'd like to have a tool that would identify the mismatch between the tools and solve it by installing necessary stuff and changing the environment variables.

**Describe alternatives you've considered**
I don't see other alternatives.

**Would you want to assign yourself to implement this feature?**
- [ ] Yes
- [x] No

**Additional context**

**Comment by JohnScience** [comment]
Most recent problem:

```
C:\Users\USER\Documents\github\betting_app\app>cargo android run
 (LM-Q630) with target "aarch64-linux-android"

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':buildSrc:compileKotlin'.
> Error while evaluating property 'compilerOptions.jvmTarget' of task ':buildSrc:compileKotlin'.
   > Failed to calculate the value of property 'jvmTarget'.
      > Unknown Kotlin JVM target: 20

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 6s
error: Failed to assemble APK
    command ["C:\\Users\\USER\\Documents\\github\\betting_app\\app\\gen\\android\\gradlew.bat", "--project-dir",
    "C:\\Users\\USER\\Documents\\github\\betting_app\\app\\gen\\android"] exited with code 1
```

Output of `gradle --version`:

```
------------------------------------------------------------
Gradle 8.3
------------------------------------------------------------
Build time:   2023-08-17 07:06:47 UTC
Revision:     8afbf24b469158b714b36e84c6f4d4976c86fcd5

Kotlin:       1.9.0
Groovy:       3.0.17
Ant:          Apache Ant(TM) version 1.10.13 compiled on January 4 2023
JVM:          20.0.2.1 (Amazon.com Inc. 20.0.2.1+10-FR)
OS:           Windows 10 10.0 amd64
```

It looks like this cause is this: https://github.com/gradle/gradle/issues/24501

**Comment by amrbashir** [comment]
I don't think we have the capacity to spend on implementing a tool to check for compatibility between gradle and gdk, if google itself didn't provide such a tool, we probably won't either. The compatibility  matrix is good enough. Also the template generated by tauri-mobile tool should be working without any compatibility issues, if you do change the template afterwards, it is your own responsibility to make them compatible.

**Comment by JohnScience** [comment]
@amrbashir I started moving in this direction. I've implemented https://crates.io/crates/corretto However, it's still *very* far from being truly useful.
