### ISSUE TITLE
WRY desktop template point to the wrong function

### ISSUE THREAD

**Issue by kettei-sproutty** [wusyong/cargo-mobile#249]
**Describe the bug**
Using the WRY template, running `cargo run`, is not possibile to run desktop example because [desktop.rs.hbs](https://github.com/tauri-apps/cargo-mobile2/blob/dev/templates/apps/wry/gen/bin/desktop.rs.hbs) should be 
```rs
{{snake-case app.name}}::main().unwrap();
``` 
and not

```rs
{{snake-case app.name}}::start_app().unwrap();
```

**Steps To Reproduce**
`cargo mobile init`
`select wry` 
`cargo run` / `cargo check`

**Expected behavior**
Desktop app should run

**Screenshots**

**Platform and Versions (please complete the following information):**
Host OS:
Target OS:
Rustc:
`cargo mobile doctor`:
(if you build with specific commit, please list it as well)

**Would you want to assign yourself to resolve this bug?**

- [x] Yes
- [ ] No

**Additional context**

**Comment by octavioCuatrochio** [comment]
I just installed it and i had this problem, thanks for the solution!
