### ISSUE TITLE
egui template crashes on load on android

### ISSUE THREAD

**Issue by Stipulations** [wusyong/cargo-mobile#386]
**Describe the bug**
on S23+ the egui example crashes instantly on open, i tried stipping down to a basic hello world and still insta crash

**Steps To Reproduce**
have s23+ and macbook air m2(both latest OS installs), follow boilerplate instructions and select egui then cargo android run

**Expected behavior**
To show egui demo

**Platform and Versions (please complete the following information):**
Host OS: MacOS
Target OS: Android
Rustc: rustc 1.81.0 (eeb90cda1 2024-09-04)
Ouput of `cargo mobile doctor`:     

cargo-mobile v0.17.0
    • Contains commits up to "chore(android): no longer needs to search the .cargo folder for links (#380)\n"
    • Installed at "~/.cargo/.cargo-mobile2"
    • macOS v14.6.1 (23G93)
    • rustc v1.81.0 (eeb90cda1 2024-9-4)

**Comment by Crashdaemon** [comment]
Hello, i am experiencing similar issues and cannot find a solution, im wondering if you found a fix Stipulations

**Comment by Stipulations** [comment]
> Hello, i am experiencing similar issues and cannot find a solution, im wondering if you found a fix Stipulations

ive yet to figure out whats causing the egui template to crash, im going to try again and see if i find anything

**Comment by marcempunkt** [comment]
Maybe it's too obvious, but nobody mentioned it, so I'm gonna do it. 

Using the default egui's eframe backend renderer instead of wgpu does not crash the app. I haven't tested it further beyond creating my own project, but it seems like its either wgpu in itself (which I doubt because there are working android egui/wgpu demos/templates out there) or rather the wgpu code inside the `create_window` and `_main` functions

**Comment by Stipulations** [comment]
> Maybe it's too obvious, but nobody mentioned it, so I'm gonna do it.
> 
> Using the default egui's eframe backend renderer instead of wgpu does not crash the app. I haven't tested it further beyond creating my own project, but it seems like its either wgpu in itself (which I doubt because there are working android egui/wgpu demos/templates out there) or rather the wgpu code inside the `create_window` and `_main` functions

I forgot to update this but compiling in release mode fixed the crashing issue.
