### ISSUE TITLE
Tauri template not shown

### ISSUE THREAD

**Issue by NoelJacob** [wusyong/cargo-mobile#46]
Sorry but noob here. Like the guide I installed everything but I only get the following output.
```
Detected template packs:
  [0] bevy
  [1] bevy-demo
  [2] wgpu
  [3] winit
  [4] wry
  Enter an index for a template pack above.
```

**Comment by lucasfernog** [comment]
To use this on tauri you need to install the CLI from tauri's next branch. We still need to update the guide :(

```
cargo install --git https://github.com/tauri-apps/tauri --branch next tauri-cli
cargo tauri android init
cargo tauri android dev
```

**Comment by NoelJacob** [comment]
Can I do ios+android+multiplatform or atleast android+multiplatform desktop at once. The command looks like only android.

**Comment by lucasfernog** [comment]
`cargo tauri ios init` and `cargo tauri ios dev` can be used for iOS. Check the [API example](https://github.com/tauri-apps/tauri/tree/next/examples/api) to see a way to setup a project for both desktop and mobile. It has a desktop binary and a mobile library, with code shared between them.

**Comment by NoelJacob** [comment]
Just a suggestion but maybe you could go the `cargo tauri init ios android` way?
