### ISSUE TITLE
wry template works fine on android, but unable to run on windows desktop

### ISSUE THREAD

**Issue by Zuzon** [wusyong/cargo-mobile#75]
![image](https://user-images.githubusercontent.com/6614645/212083342-d95b28e6-df2f-4c0a-bdaf-ccde5fd0c92b.png)

**Comment by amrbashir** [comment]
The template is meant for mobile development, for desktop, see the examples in the `wry` repo.

**Comment by amrbashir** [comment]
update in https://github.com/tauri-apps/tauri-mobile/pull/76 but still not test on iOS
