### ISSUE TITLE
cargo apple build fails since it cannot find built static libraries

### ISSUE THREAD

**Issue by DanielRWhite** [wusyong/cargo-mobile#79]
When running the build for any iOS device, including `*-apple-ios-sim` targets, the compiled static libraries are compiled to `$CARGO_MANIFEST_DIR/target`, which if you then run `cargo apple build` results in XCode not being able to find your compiled static library since it's expecting it to be in `$CARGO_MANIFEST_DIR/gen/apple/Sources`.

Simply copying the compiled target-arch folder, e.g `aarch64-apple-ios` from `target/aarch64-apple-ios` to `gen/apple/Sources/aarch64-apple-ios` will let XCode compile correctly and then you can run `cargo apple archive` to generate an installer to publish on your dev devices (Or run `cargo apple dev` to run it in the iOS sim device instead of).

Sym linking the folder from `target` to `gen/apple/Sources` didn't seem to work either, so it seems like you either need to copy the generated target arch folder each time you want to build, or override the generated cargo build output directory with `CARGO_TARGET_DIR=gen/apple/Sources cargo build --target *-apple-ios[-sim]`.

Would be nice to have this automatically copied across or set as the build output directory when running `cargo apple build`.

Note: This only affects `cargo apple build`, building from XCode, e.g to run on iOS sim, will look in the `target` folder, which is confusing.

**Comment by wusyong** [comment]
Yes the step to build library from CLI is removed due to target complexity.
Wry's doc has mentioned it to build manually both in real device and simulator:
https://github.com/tauri-apps/wry/blob/dev/MOBILE.md#ios

Note that we treat this repo more as a library and tauri CLI can actually handle that.
But welcome to contribute if you know how to determine the target archs during CLI and build it.

**Comment by DanielRWhite** [comment]
> Yes the step to build library from CLI is removed due to target complexity. Wry's doc has mentioned it to build manually both in real device and simulator: https://github.com/tauri-apps/wry/blob/dev/MOBILE.md#ios
> 
> Note that we treat this repo more as a library and tauri CLI can actually handle that. But welcome to contribute if you know how to determine the target archs during CLI and build it.

Ok, sounds good. Just checked some deeper code in this repo, just to figure it out more, seems like running `cargo apple pod install -- --clean-install` would do the required steps, but it's failing since pods it's also looking for a MacOS XCode project alongside the iOS XCode project.

Thanks for the added info though, feel free to close this if it's not an issue/needs to be brought up in a different repo. Just wanted to leave it here in case anyone else runs into the same issue, since it isn't obvious to check the Wry doc's for this info currently.

**Comment by LuisValdesZero** [comment]
Hello @DanielRWhite and @wusyong  running `cargo apple run` fails and I believe it is related to this issue.
I don't have much experience on how to solve this, can you point out what I need to do to add the library to the correct folder?

The logs 
```
cargo apple run

=== BUILD TARGET tauri-example-wry_iOS OF PROJECT tauri-example-wry WITH CONFIGURATION debug ===
ld: warning: directory not found for option '-L/Users/username/workspace/tauri-example-wry/gen/apple/Sources/aarch64-apple-ios/debug'
ld: library not found for -ltauri_example_wry
clang: error: linker command failed with exit code 1 (use -v to see invocation)
** BUILD FAILED **

error: Failed to build via `xcodebuild`
    command ["xcodebuild"] exited with code 65
```

I tried
[Unable to get IOS working on Mac M1](https://github.com/tauri-apps/tauri-mobile/issues/81#issuecomment-1419571051)  but it did not work.

**Comment by wusyong** [comment]
@kavichu Did you follow the link above? https://github.com/tauri-apps/wry/blob/dev/MOBILE.md#ios
This looks like you haven't build the library yet.

**Comment by kavichu** [comment]
> 

I did follow the steps from the link you posted.

**Comment by LuisValdesZero** [comment]
> @kavichu Did you follow the link above? https://github.com/tauri-apps/wry/blob/dev/MOBILE.md#ios This looks like you haven't build the library yet.

@wusyong  yes, I did follow the steps from the link you posted.

**Comment by wusyong** [comment]
Sorry it's my bad. I found I removed the xcode script. I'll add it back.

**Comment by wusyong** [comment]
Running `cargo mobile update --init` should regenerate the project with updated script.

**Comment by LuisValdesZero** [comment]
@wusyong Thanks for the response, I cleaned up the project, created again from scratch, but there is something wrong with the certificates, I recreated them and I have another error now. How do I reload the certificates?
Should I create another thread?

```
=== BUILD TARGET tauri-example_iOS OF PROJECT tauri-example WITH CONFIGURATION debug ===
Warning: unable to build chain to self-signed root for signer "Apple Development: me@example.com (xxxxxxxxxxxx)"
/Users/username/Library/Developer/Xcode/DerivedData/tauri-example-cwrdtenozoskffbgwhbtjwxzpfeq/Build/Products/debug-iphoneos/tauri-example.app: errSecInternalComponent
Command /usr/bin/codesign failed with exit code 1
** BUILD FAILED **

error: Failed to build via `xcodebuild`
    command ["xcodebuild"] exited with code 65
```

**Comment by wusyong** [comment]
I'm sorry certificates might be out of our reach. Usually you can have two or three devices for free certificate from a single Apple ID. But for furthermore which is common development, you will have to buy Apple Developer Enrollment.

**Comment by DanielRWhite** [comment]
>  something is wrong with the certificates

I ran into this problem myself, but the best solution I found was to use both commands `cargo tauri ios [...]` and `cargo apple [...]` depending on if I was building/deploying to iOS/other apple platforms. For some reason the `cargo tauri ios [...]` command picked up my xcode profiles and signing certificates, and ran perfectly fine on iOS simulator & physical device, but the `cargo apple [...]` command didn't work in most cases, but did for android no matter the host system. If all else fails though, and you're getting a certificate signing error in xcode itself, after the static libraries have been built and the project builds fine, it's most likely a signing error, due to you not having a valid xcode signing team setup for that app. I'm not too familiar with xcode signing teams myself, but a google search should help you out there since it's pretty well documented, you may have to pay for an app store license though, especially if you're running on physical devices/installing on devices other than your own that aren't registered to your apple developer account.

Also apologies for the late reply, but the static library issue is because tauri creates a symlink between the target/<arch>/release folder with your rust library files `yourapp.a`, `yourapp.so`, etc. and the `src-tauri/gen/apple/Sources` folder. As far as I've read through the source for tauri, it runs the build first for your app, and then updates the symlink accordingly if needed (e.g If you change from running on iOS simulator to an actual iOS device, they have different target-triplets), and then launches the xcode build. If you are running into that error, it's either because the rust code libs haven't been compiled, or the symlink is non-existant/pointing to the wrong target-triplet arch than it's expecting.

For more info on the certificates solution though, I would recommend installing `cargo tauri ios [...]` via the [tauri mobile alpha blog post](https://next--tauri.netlify.app/next/mobile/) and using `cargo tauri ios [...]` commands instead of `cargo apple [...]` for when you're building for iOS devices (Simulator/Physical). For the library issue, usually re-running `cargo tauri ios init` in your `src-tauri` folder fixes any broken symlinks that are needed, along with configs (Do note that this will override any xcode settings/configs you've setup, so it's a hard-reset in the worst case scenario). Most of the time, using `cargo tauri ios [...]` instead of `cargo apple [...]` will solve the issues you're facing though. If all else fails, try cleaning your `src-tauri/target` folder to remove any bad compiles that may be hanging around and potentially confusing things, and then run `cargo tauri ios build` again to generate a fresh compile + symlink setup.

Also, thanks @kavichu & @wusyong for the help so far, been busy, and was hoping I didn't leave this question hanging with no replies.

Feel free to give me a ping back if there's any issues, I've got this setup working for my own personal projects, but it did take a bit of trial and error to figure out. Good luck!

**Comment by wusyong** [comment]
I added a few commits to fix this recently. I think cargo apple build can work again on device and simulator.
But I still suggest using tauri CLI. This crate serves as library as README.md states.
