### ISSUE TITLE
cargo mobile init didn't created gradle file ? 

### ISSUE THREAD

**Issue by erikpa1** [wusyong/cargo-mobile#87]
Hi,

I went step by step 

```
cargo install  ...taurimobile
cargo mobile init
cargo android run
```

But I have no gradlew file here, so **cargo android run** is not working

error: Failed to assemble APK
    Command "C:\\Users\\erikp\\Desktop\\tauriandroid\\tmp\\gen\\android\\test\\gradlew.bat --project-dir
    C:\\Users\\erikp\\Desktop\\tauriandroid\\tmp\\gen\\android\\test assembleArm64Debug --warn" didn't complete
    successfully, exiting with code 1.

![image](https://user-images.githubusercontent.com/19526670/217043175-20afe670-8583-4429-ad77-be5c9be91f08.png)

**Comment by amrbashir** [comment]
I couldn't reproduce this not with the published tauri-mobile or locally. Try removing `$HOME/.tauri-mobile` and re-install tauri-mobile.

**Comment by erikpa1** [comment]
@amrbashir thanks for help, problem was, i needed "cargo mobile update", which wasn`t possible because I needed my windows in **developer mode** (first time I saw windows had developer mode,....) after enabling cargo in development mode,  I did reinstall and everything works.
