### ISSUE TITLE
cargo mobile init error: "Failed to install Rust Xcode plugin"

### ISSUE THREAD

**Issue by elliotwaite** [wusyong/cargo-mobile#95]
When I run `cargo mobile init`, it fails to install the Rust Xcode plugin with the following message:
```
...
Installing `rust-xcode-plugin`...
Updating `rust-xcode-plugin` repo...
remote: Total 0 (delta 0), reused 0 (delta 0), pack-reused 0
fatal: ambiguous argument 'origin/dev': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
action request: Failed to install Rust Xcode plugin; this component is optional, so init will continue anyway, but Xcode debugging won't work until this is resolved!
    Failed to reset repo: Command "git -C /Users/elliotwaite/.tauri-mobile/checkouts/rust-xcode-plugin reset --hard origin/dev" didn't complete successfully, exiting with code 128.
...
```

The part of the error message that says `ambiguous argument 'origin/dev'` seems to related to the fact that the [tauri-apps/rust-xcode-plugin](https://github.com/tauri-apps/rust-xcode-plugin) repo [doesn't have a dev branch](https://github.com/tauri-apps/rust-xcode-plugin/branches).

Changing the git command from this:
```
git -C /Users/elliotwaite/.tauri-mobile/checkouts/rust-xcode-plugin reset --hard origin/dev
```
to this:
```
git -C /Users/elliotwaite/.tauri-mobile/checkouts/rust-xcode-plugin reset --hard origin/master
```
seemed to make that git command work, but I wasn't sure how to update this repo to use that command instead (I'm new to Rust and this repo).

**Comment by pewsheen** [comment]
It seems related to #86 

Maybe we can make the repo.update() to accept a target branch.
